### ISSUE TITLE
Clean up azmpmap popups

### ISSUE THREAD

**Issue by j-harbin** [casaultb/azmpdata#55]
* [ ] Remove years
* [ ] Remove parameters

@MMMcMahon I'll assign this to you, since you're the "azmpmap guy" :).

**Comment by MMMcMahon** [comment]
to This should be revisited (and maybe closed).  My most recent commit cleaned the popups on azmpmap dramatically.  

Years:  I didn't remove them, but I identified the range, and still report the first and last year data was collected - e.g. "1870 to 2020" (instead of listing all years).

Parameters:  I did remove them.
